version: "3"
services:
  apigility:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "81:8080"
    volumes:
     - .:/var/www
    command:  sh -c "composer install && /usr/sbin/apache2ctl -DFOREGROUND "

